"""add scaler_path column to logs table

Revision ID: 53d74044e96b
Revises: d7db7eff6458
Create Date: 2025-05-17 23:50:32.513545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53d74044e96b'
down_revision = 'd7db7eff6458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('scaler_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('scaler_path')
        batch_op.drop_column('model_path')

    # ### end Alembic commands ###
