"""add classification_report column to logs table

Revision ID: d7db7eff6458
Revises: 190bc84d29f6
Create Date: 2025-05-17 22:01:32.097551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7db7eff6458'
down_revision = '190bc84d29f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_report', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('classification_report')

    # ### end Alembic commands ###
